apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-showtimes-deployment
  labels:
    app: cinema-showtimes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinema-showtimes
  template:
    metadata:
      labels:
        app: cinema-showtimes
    spec:
      containers:
      - name: cinema-showtimes
        image: irahardianto/cinema-showtimes:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: cinema-showtimes-svc
spec: 
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector: 
    app: cinema-showtimes
  type: NodePort
