apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-bookings-deployment
  labels:
    app: cinema-bookings
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinema-bookings
  template:
    metadata:
      labels:
        app: cinema-bookings
    spec:
      containers:
      - name: cinema-bookings
        image: irahardianto/cinema-bookings:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: cinema-bookings-svc
spec: 
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector: 
    app: cinema-bookings
  type: NodePort
