apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-users-deployment
  labels:
    app: cinema-users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinema-users
  template:
    metadata:
      labels:
        app: cinema-users
    spec:
      containers:
      - name: cinema-users
        image: irahardianto/cinema-users:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: cinema-users-svc
spec: 
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector: 
    app: cinema-users
  type: NodePort
