apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-movies-deployment
  labels:
    app: cinema-movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cinema-movies
  template:
    metadata:
      labels:
        app: cinema-movies
    spec:
      containers:
      - name: cinema-movies
        image: irahardianto/cinema-movies:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: cinema-movies-svc
spec: 
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector: 
    app: cinema-movies
  type: NodePort
